{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-secrets
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_PASS: {{ .Values.smtp.pass | quote }}
{{- end }}
