name: Build, Push, and Deploy Ayur App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: shubham554/ayur-app
      IMAGE_TAG: build-${{ github.run_number }}
      FULL_IMAGE: shubham554/ayur-app:build-${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.FULL_IMAGE }}

      - name: Update docker-compose.yml with new image tag
        run: |
          echo "Updating image tag in docker-compose.yml..."
          sed -i "s|image: shubham554/ayur-app:.*|image: shubham554/ayur-app:build-${{ github.run_number }}|" docker-compose.yml
          echo "Updated file content:"
          cat docker-compose.yml

      #- name: Run docker-compose up
      #  run: |
      #    docker-compose pull
      #    docker-compose up -d --remove-orphans
