name: Build, Push and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/ayur-app
      IMAGE_TAG: build-${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Update docker-compose.yml with new image tag
        run: |
          sed -i "s|image: .*$|image: ${IMAGE_NAME}:${IMAGE_TAG}|" docker-compose.yml

      - name: Run docker-compose up
        run: |
          docker-compose pull
          docker-compose up -d --remove-orphans
